name = "Toadland Modpack"
author = "Toadland"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e509d566166c9b77d831500196c31ddd810c8a9c1fa45568521119a4b1db7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
