name = "Toadland Modpack"
author = "Toadland"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f81045e3e2e783b01f261f28105e77e8b2ccf801e614fbb120be15917bcbcc5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
